name: Pulumi Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Pulumi CLI
        run: |
          curl -fsSL https://get.pulumi.com | sh
          export PATH=$PATH:$HOME/.pulumi/bin

      - name: Configure Pulumi
        run: pulumi login --cloud-url https://management.azure.com

      - name: Pulumi Preview
        run: pulumi preview

      - name: Pulumi Deploy
        run: pulumi up --yes
